version: '3.7'
services:
  worker:
    build:
      context: worker
      args:
        - PKG=${WORKER_PKG}
    volumes:
      - "./worker/:/app"
    restart: on-failure
  grpcs:
    build:
      context: grpcs
      args:
        - PKG=${GRPCS_PKG}
        - GRPC_SERVICE_ACCESS_PORT=${GRPC_SERVICE_ACCESS_PORT}
    volumes:
      - "./grpcs/:/app"
    restart: on-failure
    ports:
       - "${GRPC_SERVICE_ACCESS_PORT}:${GRPC_SERVICE_ACCESS_PORT}"
  # api:
  #   build:
  #     context: api
  #     args:
  #       - API_ACCESS_PORT=${API_ACCESS_PORT}
  #   volumes:
  #     - "./api/:/app"
  #   ports:
  #     - "${API_ACCESS_PORT}:${API_ACCESS_PORT}"
  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
      - 'bootstrap.memory_lock=true'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'xpack.security.enrollment.enabled=false'
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:8.11.1
    ports:
      - "5601:5601"