version: '3.7'
services:
  worker:
    env_file:
      - .env
    build:
      context: worker
    volumes:
      - "./worker/:/app"
  grpcs:
    env_file:
        - .env
    build:
      context: grpcs
    volumes:
      - "./grpcs/:/app"
  api:
    env_file:
      - .env
    build:
      context: api
      args:
        - API_ACCESS_PORT=${API_ACCESS_PORT}
    volumes:
      - "./api/:/app"
    ports:
      - "${API_ACCESS_PORT}:${API_ACCESS_PORT}"
  elasticsearch:
    image: elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  